##Курсовая работа по дисциплине "Искусственный интеллект. Машиннное обучение и анализ данных"

**Постановка задачи**

На основании имеющихся данных о клиентах банка требуется построить модель для прогнозирования невыполнения долговых обязательств по текущему кредиту. Выполнить прогноз для примеров из тестового датасета.

**Наименование файлов с данными**

course_project_train.csv - обучающий датасет<br>
course_project_test.csv - тестовый датасет  

Из тестового датасета удалять строки никак нельзя!

**Целевая переменная**

Credit Default - факт невыполнения кредитных обязательств (класс 1 - просрочка по кредиту)

**Метрика качества**

f1-score (sklearn.metrics.f1_score)

**Требования к решению**

*Целевая метрика*
* f1 >= 0.5 при Precision > 0.5 и Recall > 0.5 - максимальная оценка 5-ка  
* 0.5 > f1 >= 0.4 при Precision > 0.4 и Recall > 0.4 - максимальная оценка 4-ка  
* 0.4 > f1 >= 0.3 - максимальная оценка 3-ка  
* Метрика оценивается по качеству прогноза для главного класса (1 - просрочка по кредиту)

*Решение должно содержать*
1. Тетрадка Jupyter Notebook с кодом Вашего решения, названная по образцу {ФИО}\_solution.ipynb, пример Telina\_solution.ipynb
2. Файл CSV с прогнозами целевой переменной **(класс 0 или 1, а НЕ вероятность)** для тестового датасета, названный по образцу {ФИО}\_predictions.csv, пример Telina\_predictions.csv
3. Отчет по курсовой работе в формате {ФИО}\_report.docx

*Рекомендации для файла с кодом (ipynb)*
1. Файл должен содержать заголовки и комментарии (markdown)
2. Повторяющиеся операции лучше оформлять в виде функций
3. Не делать вывод большого количества строк таблиц (5-10 достаточно)
4. Обязательно добавить диаграммы и графики с выводами по ним
5. Добавлять только лучшую модель, то есть не включать в код все варианты решения проекта, но написать, почему была выбрана именно эта модель
6. Скрипт проекта должен отрабатываться от начала и до конца (от загрузки данных до выгрузки предсказаний)

*Этапы работы (рекомендуемые)*
1. Провести анализ данных. Найти пропуски, аномальные значения, категории. Оценить распределения признаков и целевой переменной.
2. Выполнить очистку данных в обоих датасетах - обработать пропуски и аномальные значения, заменить категории на числа. Удалять или добавлять столбцы можно в трейне и тесте. Удалять строки можно только в трейне (обучающей выборке). В тесте (тестовой выборке) должно оставаться 2500 строк без изменений.   
3. Найти наиболее значимые признаки для целевой переменной.
4. Создать новые признаки.
5. Обучить базовую модель и оценить ее точность на отложенной выборке или с использованием кросс-валидации.
6. Проверить другие модели и выбрать наилучшую.
7. Подобрать гиперпараметры модели.
8. Получить прогнозы для данных из датасета course_project_test.csv.

**Защита работы**

На защите работы будут вопросы по некоторым используемым моделям, метрикам и методам.
Оценки работ будут представлены в виде рейтинга, ранжированного по заданной метрике качества.

In [ ]:
import pandas as pd

**Обучающий датасет**

In [ ]:
!gdown 1bYG4-UoC6WptPTOVQwQZ6PANcBaLH1Qj
df = pd.read_csv('/content/course_project_train.csv')
df.head()

Downloading...
From: https://drive.google.com/uc?id=1bYG4-UoC6WptPTOVQwQZ6PANcBaLH1Qj
To: /content/course_project_train.csv
100% 908k/908k [00:00<00:00, 71.0MB/s]

,Home Ownership,Annual Income,Years in current job,Tax Liens,Number of Open Accounts,Years of Credit History,Maximum Open Credit,Number of Credit Problems,Months since last delinquent,Bankruptcies,Purpose,Term,Current Loan Amount,Current Credit Balance,Monthly Debt,Credit Score,Credit Default
0,Own Home,482087.0,NaN,0.0,11.0,26.3,685960.0,1.0,NaN,1.0,debt consolidation,Short Term,99999999.0,47386.0,7914.0,749.0,0
1,Own Home,1025487.0,10+ years,0.0,15.0,15.3,1181730.0,0.0,NaN,0.0,debt consolidation,Long Term,264968.0,394972.0,18373.0,737.0,1
2,Home Mortgage,751412.0,8 years,0.0,11.0,35.0,1182434.0,0.0,NaN,0.0,debt consolidation,Short Term,99999999.0,308389.0,13651.0,742.0,0
3,Own Home,805068.0,6 years,0.0,8.0,22.5,147400.0,1.0,NaN,1.0,debt consolidation,Short Term,121396.0,95855.0,11338.0,694.0,0
4,Rent,776264.0,8 years,0.0,13.0,13.6,385836.0,1.0,NaN,0.0,debt consolidation,Short Term,125840.0,93309.0,7180.0,719.0,0

In [ ]:
df.shape

(7500, 17)

**Тестовый датасет**

In [ ]:
!gdown 11haItNAFR2O_0A4Qilox58h27JrGNoDM
df_test = pd.read_csv('/content/course_project_test.csv')
df_test.head()

Downloading...
From: https://drive.google.com/uc?id=11haItNAFR2O_0A4Qilox58h27JrGNoDM
To: /content/course_project_test.csv
100% 298k/298k [00:00<00:00, 44.0MB/s]

,Home Ownership,Annual Income,Years in current job,Tax Liens,Number of Open Accounts,Years of Credit History,Maximum Open Credit,Number of Credit Problems,Months since last delinquent,Bankruptcies,Purpose,Term,Current Loan Amount,Current Credit Balance,Monthly Debt,Credit Score
0,Rent,NaN,4 years,0.0,9.0,12.5,220968.0,0.0,70.0,0.0,debt consolidation,Short Term,162470.0,105906.0,6813.0,NaN
1,Rent,231838.0,1 year,0.0,6.0,32.7,55946.0,0.0,8.0,0.0,educational expenses,Short Term,78298.0,46037.0,2318.0,699.0
2,Home Mortgage,1152540.0,3 years,0.0,10.0,13.7,204600.0,0.0,NaN,0.0,debt consolidation,Short Term,200178.0,146490.0,18729.0,7260.0
3,Home Mortgage,1220313.0,10+ years,0.0,16.0,17.0,456302.0,0.0,70.0,0.0,debt consolidation,Short Term,217382.0,213199.0,27559.0,739.0
4,Home Mortgage,2340952.0,6 years,0.0,11.0,23.6,1207272.0,0.0,NaN,0.0,debt consolidation,Long Term,777634.0,425391.0,42605.0,706.0

In [ ]:
df_test.shape

(2500, 16)

In [ ]:
#